# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_row_type_section_num.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winRowType(object):
    def setupUi(self, winRowType):
        winRowType.setObjectName("winRowType")
        winRowType.resize(1000, 600)
        winRowType.setMinimumSize(QtCore.QSize(1000, 600))
        winRowType.setMaximumSize(QtCore.QSize(1000, 600))
        self.btnNext = QtWidgets.QPushButton(winRowType)
        self.btnNext.setGeometry(QtCore.QRect(650, 400, 131, 31))
        self.btnNext.setMinimumSize(QtCore.QSize(71, 21))
        self.btnNext.setMaximumSize(QtCore.QSize(131, 31))
        self.btnNext.setObjectName("btnNext")
        self.btnCheck = QtWidgets.QPushButton(winRowType)
        self.btnCheck.setGeometry(QtCore.QRect(500, 400, 131, 31))
        self.btnCheck.setMinimumSize(QtCore.QSize(71, 21))
        self.btnCheck.setMaximumSize(QtCore.QSize(131, 31))
        self.btnCheck.setObjectName("btnCheck")
        self.verticalLayoutWidget = QtWidgets.QWidget(winRowType)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 438, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.lblNumSect = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNumSect.setObjectName("lblNumSect")
        self.horizontalLayout_1.addWidget(self.lblNumSect)
        self.lineEditNUmSect = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditNUmSect.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEditNUmSect.setMaximumSize(QtCore.QSize(100, 20))
        self.lineEditNUmSect.setObjectName("lineEditNUmSect")
        self.horizontalLayout_1.addWidget(self.lineEditNUmSect)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.lineEditErrorCheck = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditErrorCheck.setMaximumSize(QtCore.QSize(190, 20))
        self.lineEditErrorCheck.setObjectName("lineEditErrorCheck")
        self.horizontalLayout_1.addWidget(self.lineEditErrorCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rBtn_strout = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rBtn_strout.setObjectName("rBtn_strout")
        self.horizontalLayout_2.addWidget(self.rBtn_strout)
        self.rBtn_igv = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rBtn_igv.setObjectName("rBtn_igv")
        self.horizontalLayout_2.addWidget(self.rBtn_igv)
        self.rBtn_rotor = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rBtn_rotor.setObjectName("rBtn_rotor")
        self.horizontalLayout_2.addWidget(self.rBtn_rotor)
        self.rBtn_stator = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rBtn_stator.setObjectName("rBtn_stator")
        self.horizontalLayout_2.addWidget(self.rBtn_stator)
        self.rBtn_ogv = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rBtn_ogv.setObjectName("rBtn_ogv")
        self.horizontalLayout_2.addWidget(self.rBtn_ogv)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(winRowType)
        QtCore.QMetaObject.connectSlotsByName(winRowType)

    def retranslateUi(self, winRowType):
        _translate = QtCore.QCoreApplication.translate
        winRowType.setWindowTitle(_translate("winRowType", "Form"))
        self.btnNext.setText(_translate("winRowType", "next"))
        self.btnCheck.setText(_translate("winRowType", "check"))
        self.lblNumSect.setText(_translate("winRowType", "number of sections"))
        self.rBtn_strout.setText(_translate("winRowType", "strout"))
        self.rBtn_igv.setText(_translate("winRowType", "igv"))
        self.rBtn_rotor.setText(_translate("winRowType", "rotor"))
        self.rBtn_stator.setText(_translate("winRowType", "stator"))
        self.rBtn_ogv.setText(_translate("winRowType", "ogv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    winRowType = QtWidgets.QWidget()
    ui = Ui_winRowType()
    ui.setupUi(winRowType)
    winRowType.show()
    sys.exit(app.exec_())
